services:
  app:
    build: .
    working_dir: /home/app
    ports:
      - 3000:3000
      - 9005:9005 # for firebase cli
    volumes:
      - .:/home/app
    tty: true
    stdin_open: true
    command: npm run dev